---
# tasks file for apigee-opdk-setup-provisioning
- name: Obtain apigee-provision status
  stat:
    path: '{{ apigee_provision_dir }}'
  register: apigee_provision_status

- name: Apigee provision installation
  shell: '{{ apigee_service }} apigee-provision install'
  when: not apigee_provision_status.stat.exists

- name: Apigee organization setup
  shell: '{{ apigee_service }} apigee-provision {{ provisioning_action }} -f {{ provisioning_config_file }}'
  ignore_errors: yes
